sensor_msgs/Image input_map			# the action server need a map as a input image to segment it, IMPORTANT: The algorithm needs a black and white 8bit single-channel image, which is 0 (black) for obstacles and 256 (white) for free space
geometry_msgs/Pose2D[] path			# check the coverage along this path, in the world frame [meter]
geometry_msgs/Point32[] field_of_view		# the points that define the field of view of the robot, relatively to the robot, [meter], counter-clock-wise starting from left, nearer to robot point, assumed to be 4 different points in the right halfplane of the two dimensional space
geometry_msgs/Point32[] footprint		# footprint of the interesting part of the robot, for which a coverage path planning should be done (e.g. the cleaning part), relatively to the robot [meter]
bool check_for_footprint			# determine, if the coverage check should be done for the footprint or the field of view
float32 map_resolution				# resolution of the given map, [meter/cell]
geometry_msgs/Pose2D map_origin			# the origin of the map in [meter]
---
sensor_msgs/Image coverage_map		# the map that has the covered areas drawn in, with a value of 127, also a 8bit single-channel image
